# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/devooty/Downloads/Encryptor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/devooty/Downloads/Encryptor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/devooty/Downloads/Encryptor/CMakeFiles /home/devooty/Downloads/Encryptor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/devooty/Downloads/Encryptor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Encryptor

# Build rule for target.
Encryptor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Encryptor
.PHONY : Encryptor

# fast build rule for target.
Encryptor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/build
.PHONY : Encryptor/fast

src/encryption/decrypt.o: src/encryption/decrypt.cpp.o
.PHONY : src/encryption/decrypt.o

# target to build an object file
src/encryption/decrypt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryption/decrypt.cpp.o
.PHONY : src/encryption/decrypt.cpp.o

src/encryption/decrypt.i: src/encryption/decrypt.cpp.i
.PHONY : src/encryption/decrypt.i

# target to preprocess a source file
src/encryption/decrypt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryption/decrypt.cpp.i
.PHONY : src/encryption/decrypt.cpp.i

src/encryption/decrypt.s: src/encryption/decrypt.cpp.s
.PHONY : src/encryption/decrypt.s

# target to generate assembly for a file
src/encryption/decrypt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryption/decrypt.cpp.s
.PHONY : src/encryption/decrypt.cpp.s

src/encryption/encrypt.o: src/encryption/encrypt.cpp.o
.PHONY : src/encryption/encrypt.o

# target to build an object file
src/encryption/encrypt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryption/encrypt.cpp.o
.PHONY : src/encryption/encrypt.cpp.o

src/encryption/encrypt.i: src/encryption/encrypt.cpp.i
.PHONY : src/encryption/encrypt.i

# target to preprocess a source file
src/encryption/encrypt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryption/encrypt.cpp.i
.PHONY : src/encryption/encrypt.cpp.i

src/encryption/encrypt.s: src/encryption/encrypt.cpp.s
.PHONY : src/encryption/encrypt.s

# target to generate assembly for a file
src/encryption/encrypt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryption/encrypt.cpp.s
.PHONY : src/encryption/encrypt.cpp.s

src/encryptor.o: src/encryptor.cpp.o
.PHONY : src/encryptor.o

# target to build an object file
src/encryptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryptor.cpp.o
.PHONY : src/encryptor.cpp.o

src/encryptor.i: src/encryptor.cpp.i
.PHONY : src/encryptor.i

# target to preprocess a source file
src/encryptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryptor.cpp.i
.PHONY : src/encryptor.cpp.i

src/encryptor.s: src/encryptor.cpp.s
.PHONY : src/encryptor.s

# target to generate assembly for a file
src/encryptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/encryptor.cpp.s
.PHONY : src/encryptor.cpp.s

src/shell/shell.o: src/shell/shell.cpp.o
.PHONY : src/shell/shell.o

# target to build an object file
src/shell/shell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/shell/shell.cpp.o
.PHONY : src/shell/shell.cpp.o

src/shell/shell.i: src/shell/shell.cpp.i
.PHONY : src/shell/shell.i

# target to preprocess a source file
src/shell/shell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/shell/shell.cpp.i
.PHONY : src/shell/shell.cpp.i

src/shell/shell.s: src/shell/shell.cpp.s
.PHONY : src/shell/shell.s

# target to generate assembly for a file
src/shell/shell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/shell/shell.cpp.s
.PHONY : src/shell/shell.cpp.s

src/tools/edir.o: src/tools/edir.cpp.o
.PHONY : src/tools/edir.o

# target to build an object file
src/tools/edir.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/tools/edir.cpp.o
.PHONY : src/tools/edir.cpp.o

src/tools/edir.i: src/tools/edir.cpp.i
.PHONY : src/tools/edir.i

# target to preprocess a source file
src/tools/edir.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/tools/edir.cpp.i
.PHONY : src/tools/edir.cpp.i

src/tools/edir.s: src/tools/edir.cpp.s
.PHONY : src/tools/edir.s

# target to generate assembly for a file
src/tools/edir.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/tools/edir.cpp.s
.PHONY : src/tools/edir.cpp.s

src/tools/eprint.o: src/tools/eprint.cpp.o
.PHONY : src/tools/eprint.o

# target to build an object file
src/tools/eprint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/tools/eprint.cpp.o
.PHONY : src/tools/eprint.cpp.o

src/tools/eprint.i: src/tools/eprint.cpp.i
.PHONY : src/tools/eprint.i

# target to preprocess a source file
src/tools/eprint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/tools/eprint.cpp.i
.PHONY : src/tools/eprint.cpp.i

src/tools/eprint.s: src/tools/eprint.cpp.s
.PHONY : src/tools/eprint.s

# target to generate assembly for a file
src/tools/eprint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Encryptor.dir/build.make CMakeFiles/Encryptor.dir/src/tools/eprint.cpp.s
.PHONY : src/tools/eprint.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Encryptor"
	@echo "... src/encryption/decrypt.o"
	@echo "... src/encryption/decrypt.i"
	@echo "... src/encryption/decrypt.s"
	@echo "... src/encryption/encrypt.o"
	@echo "... src/encryption/encrypt.i"
	@echo "... src/encryption/encrypt.s"
	@echo "... src/encryptor.o"
	@echo "... src/encryptor.i"
	@echo "... src/encryptor.s"
	@echo "... src/shell/shell.o"
	@echo "... src/shell/shell.i"
	@echo "... src/shell/shell.s"
	@echo "... src/tools/edir.o"
	@echo "... src/tools/edir.i"
	@echo "... src/tools/edir.s"
	@echo "... src/tools/eprint.o"
	@echo "... src/tools/eprint.i"
	@echo "... src/tools/eprint.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

